sonar.projectKey=SGT-Gemini-Pro
sonar.projectName=SGT-Gemini-Pro
sonar.host.url=http://localhost:9000
sonar.token=sqa_f3018dee25a98d6140759a89ef382bf12f712a10
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/coverage/**